//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanvemaybay1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETCHUYENBAY()
        {
            this.CHUYENBAYs = new HashSet<CHUYENBAY>();
            this.VEMAYBAYs = new HashSet<VEMAYBAY>();
        }
    
        public string MaChiTietChuyenBay { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> GioDi { get; set; }
        public Nullable<System.TimeSpan> GioDen { get; set; }
        public string Sandi { get; set; }
        public string Sanden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENBAY> CHUYENBAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEMAYBAY> VEMAYBAYs { get; set; }
    }
}
