//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanvemaybay1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOIHANHLY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOIHANHLY()
        {
            this.PHIEUKYGUIHANHLies = new HashSet<PHIEUKYGUIHANHLY>();
        }
    
        public string MaGoi { get; set; }
        public string TenGoi { get; set; }
        public Nullable<int> GiaGoi { get; set; }
        public Nullable<int> SoKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUKYGUIHANHLY> PHIEUKYGUIHANHLies { get; set; }
    }
}
