//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanvemaybay1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEMAYBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEMAYBAY()
        {
            this.PHIEUDOIHUYVEs = new HashSet<PHIEUDOIHUYVE>();
        }
    
        public string MaVe { get; set; }
        public string MaKH { get; set; }
        public string MaChiTietChuyenBay { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> GioDi { get; set; }
        public Nullable<System.TimeSpan> GioDen { get; set; }
        public string Sandi { get; set; }
        public string Sanden { get; set; }
    
        public virtual CHITIETCHUYENBAY CHITIETCHUYENBAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDOIHUYVE> PHIEUDOIHUYVEs { get; set; }
    }
}
